### ISSUE TITLE
System.InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.

### ISSUE THREAD

**Issue by GODBS** [grandchamp/Identity.Dapper#61]
I believe there is an issue when the primary key is a GUID.

The issue is probably on line 260 in the DapperUserStore
`var result = await _userRepository.GetByIdAsync((TKey)Convert.ChangeType(userId, typeof(TKey)));`

this could maybe be an alternative:

`T t = (T)TypeDescriptor.GetConverter(typeof(T)).ConvertFromInvariantString(text);`

https://stackoverflow.com/questions/393731/generic-conversion-function-doesnt-seem-to-work-with-guids#393787

**Comment by grandchamp** [comment]
Can you make a test to reproduce and propose a fix?

**Comment by grandchamp** [comment]
Closed as i don't had any interaction from OP

**Comment by dango85** [comment]
I did run into similar error when using guid's as ID type. Basically the problem is definition IUserStore.FindByIdAsync(string userId, CancellationToken cancellationToken). The convert method implemented in DapperUserStore.cs Line 237 cannot convert string to guid.
To fix this I added additional condition to check type before converting to TKey.

![image](https://user-images.githubusercontent.com/5007593/43499419-faeef27a-9510-11e8-85d3-dbcdf553b067.png)
